### PR TITLE
#727 disable gpu accelerate , fix the GPU render problem

### PR DESCRIPTION
**Pull request by netroby**

### CODE REVIEW

**Comment by eliykat** [comment]
Hi @netroby, thanks for your submission! I'm currently reviewing and cleaning up old pull requests. If you're still interested in progressing this PR, please:
* sign the Contributor License Agreement (see the link provided by the CLAassistant bot above)
* reply here and tag me (@) so that I can mark it for further review

As you have not signed the CLA, I'll close this for now. However, this is just housekeeping. We encourage our community members to get involved and make contributions, so you can comment here even after it's closed and I'll reopen it if required.

**Comment by netroby** [comment]
image
@eliykat I already signed the CLA

**Comment by Hinton** [comment]
Hi @netroby,

Appoligies for the late review.

We can't disable GPU acceleration for all users since it works fine for the large majority. It would need to be a setting that can be toggled by the user in the preferences. Let me know if you are willing to update this PR wich such a setting.

**Comment by Hinton** [comment]
Hi @netroby,

We haven't heard from you in a while, and will close this PR for now. Feel free to open a new PR after addressing the comments.

**Pull request closed without merging**
