### PR TITLE
Update electron to 11.1.1

### PR DESCRIPTION
**Pull request by Hinton**
Relevant electron deprecations:
* In-app purchase apis have been updated to use promises.
* `systemPreferences.isDarkMode()` is replaced with `nativeTheme.shouldUseDarkColors`.

Depends on: https://github.com/bitwarden/jslib/pull/247

### CODE REVIEW

**Review by cscharf — COMMENTED** [review]
Looks good, waiting on `jslib` update

**Comment by kspearrin** [comment]
we might want to wait to merge this after this coming release, too.

**Comment by cscharf** [comment]
> we might want to wait to merge this after this coming release, too.

Absolutely, I have a `hold` label on it as a reminder not to merge this in yet.

**Comment by flying-sausages** [comment]
A question about the implications of this getting merged: Any expectation of this contributing to Apple Silicon support directly, or would it need extra work you reckon?

I'd be happy to test this with the dep merged on my hardware if that would help advance things, would fork the discussion off somewhere else to not clutter this PR.

**Comment by cscharf** [comment]
@Hinton , good to merge `jslib` update and pull that into this PR, build should work after that. Then this can be approved/merged in.

@flying-sausages, re:
> A question about the implications of this getting merged: Any expectation of this contributing to Apple Silicon support directly, or would it need extra work you reckon?
> 
> I'd be happy to test this with the dep merged on my hardware if that would help advance things, would fork the discussion off somewhere else to not clutter this PR.

This gets us mostly there, after this is merged we still need to work through packaging and preparation of the appropriate MAS packages, process, etc. to ensure the right versions are available to those on M1 hardware.

**Review by cscharf — APPROVED** [review]

**Pull request merged**
