### PR TITLE
Allow app to start minimized (as tray icon)

### PR DESCRIPTION
**Pull request by h44z**
If this setting is enabled, the main window will be hidden after startup. Disabled by default.

This is useful if Bitwarden gets started automatically after boot.

Needed jslib changes: https://github.com/bitwarden/jslib/pull/22

### CODE REVIEW

**Comment by h44z** [comment]
@kspearrin any thoughts on this?

**Comment by kspearrin** [comment]
How is Bitwarden getting started automatically after boot? I don't think that is supported at the moment.

**Comment by h44z** [comment]
On Windows: simply put a link to bitwarden.exe to your autostart folder

**Comment by BrMBr** [comment]
It needs to start minimized on Linux as well.

**Pull request merged**
