### PR TITLE
#281 Update libraries fixing high vulnerabilities

### PR DESCRIPTION
**Pull request by javawithjiva**
Fixes the 239 HIGH vulnerabilities as mentioned by `npm audit`

### CODE REVIEW

**Comment by javawithjiva** [comment]
Can someone please review and merge?

**Comment by javawithjiva** [comment]
Anyone?

**Comment by immanuelfodor** [comment]
Shouldn't such highly security-related PR be treated with more welcome? :) Thumbs up for pushing this fix, I hope it can be merged soon. Maybe we should tag maintainers of this repo to get more attention, e.g., @kspearrin ?

**Comment by kspearrin** [comment]
Resolved with https://github.com/bitwarden/desktop/commit/d952ce27bce0c8486befad2539b5320a514d1992

Thanks

**Pull request closed without merging**
