### PR TITLE
fix: Edge supported by biometrics

### PR DESCRIPTION
**Pull request by aimuz**
reference resources: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=macos

### CODE REVIEW

**Review by Hinton — DISMISSED** [review]

**Comment by Hinton** [comment]
@aimuz Did you have issues using browser biometrics on Edge before making these changes?

On Windows the `Computer\HKEY_CURRENT_USER\SOFTWARE\Google\Chrome` registry directory seems to always exist even on a fresh install without Chrome. Since Edge seems to fallback to this path things should work fine on Windows.

It might be different on Mac and Linux though, so to be safe these changes should ensure we always have the manifest available even if Chrome is not installed. 👍

**Comment by aimuz** [comment]
I've been tested on MacOS and it works. I don't have a biometric Linux device, but I think it works.According to the edge document, there should be no risk of such a change

If it works on Windows itself, I will return the changes to windows

**Comment by aimuz** [comment]
If you have the relevant equipment, I hope you can help me

**Review by Hinton — APPROVED** [review]

**Comment by Hinton** [comment]
Confirmed Edge works on a clean Windows VM without chrome on currently released version.

**Comment by aimuz** [comment]
Very good. When can we merge?

**Comment by cscharf** [comment]
Please note, while merged this will not be released in the currently planned release as we've already cut our release candidates and are wrapping up regression testing, but should be in the next release.

**Pull request merged**
