### PR TITLE
Update macOS icon to follow Big Sur design

### PR DESCRIPTION
**Pull request by hollow-frenk**
First of all, a greeting to you who will review my contribution, I already know that an icon for Big Sur has already been created and accepted but I wanted to bring my work to your attention because, in my opinion, it is more in line with the Big Sur guidelines.
The icon was created using Apple's official icon template, using the same gradient as the Bitwarden icon for iOS.
Unlike the current icon, the shield is completely white with the addition of internal and external shadows. (I attach the .fig file for further information and / or changes)
[macOS Big Sur Bitwarden Icon Template.fig.zip](https://github.com/bitwarden/desktop/files/6307808/macOS.Big.Sur.Bitwarden.Icon.Template.fig.zip)

### CODE REVIEW

**Comment by cscharf** [comment]
Thanks @hollow-frenk , seems that the inner-shadow/bezel presented in these makes the shield appear "fuzzy" and it takes a minute or two of really focusing in to clear it up to the eye before going, "oh, I see now, it's bezeled". I'm not sure this makes a marked improvement over the existing version already submitted. @tgreer-bw ?

**Comment by tgreer-bw** [comment]
@cscharf agreed. @hollow-frenk thank you for your work, though! We'll run with the first update for a bit and then see if we need any polishing steps.

**Comment by hollow-frenk** [comment]
Thanks for the feedback, I am working on some improvements which I will then submit to you hoping you will like them.

**Comment by hollow-frenk** [comment]
@cscharf @tgreer-bw Hi, I reworked the icon, take a look at it.  Thanks for your time.

**Comment by tgreer-bw** [comment]
@hollow-frenk - Thanks again. The icons are both great, so we're having our design/brand team review and we'll merge the approved set.

**Comment by hollow-frenk** [comment]
@tgreer-bw Ok, then as soon as possible I am attaching the source file

**Comment by Hinton** [comment]
Hi @hollow-frenk,

Just wanted to let you know that I've updated the icons per our design team requests and we'll be looking into getting this merged shortly.

@danielleflinn Can you verify that the icons matches the icons in Asana?
@djsmith85 mind approving this PR?

**Comment by hollow-frenk** [comment]
Asana?

**Review by danielleflinn — APPROVED** [review]
looks good!

**Review by djsmith85 — APPROVED** [review]
Also looks good to me. 

@Hinton Please check if we can/should also update the icons presented here: https://github.com/bitwarden/browser/pull/2058

**Comment by hollow-frenk** [comment]
Se volete, procedo anche con la versione iOS...

**Pull request merged**
