### PR TITLE
Add locale info for hint equals password

### PR DESCRIPTION
**Pull request by cwille97**

### CODE REVIEW

**Comment by cscharf** [comment]
@cwille97 , can you please revert the jslib change in this MR/PR? That should resolve any conflict issues there.

**Comment by cwille97** [comment]
@cscharf I just got off work and saw a bunch of emails related to my PRs here, do I still need to revert any changes or is everything all good to go?

**Comment by cscharf** [comment]
> I still need to revert any changes or is everything all good to go?

Hi @cwille97 , yes, still need you to revert the update to jslib in this PR if you could, thanks!

**Comment by cwille97** [comment]
@cscharf Does this work? I think for some reason it combined my change to the json file with a bunch of translations, but I removed jslib.

**Review by cscharf — APPROVED** [review]

**Comment by cscharf** [comment]
Closing this PR, needed to perform merge conflict in new PR, see https://github.com/bitwarden/desktop/pull/616

**Pull request closed without merging**
