### PR TITLE
package: Package ARM64 binaries for Linux

### PR DESCRIPTION
**Pull request by alistair23**
This adds support for Aarch64 builds.

This is aiming to address: https://github.com/flathub/com.bitwarden.desktop/issues/63

Signed-off-by: Alistair Francis <alistair@alistair23.me>

### CODE REVIEW

**Comment by alistair23** [comment]
Ping!

**Comment by baarkerlounger** [comment]
@Hinton would you be able to take a look at this?

**Review by joseph-flinn — CHANGES_REQUESTED** [review]
The `upload-artifact` GitHub Action does not support uploading multiple artifacts from the same step. Please see the documentation here: https://github.com/actions/upload-artifact

**Comment by alistair23** [comment]
Fixed

**Comment by joseph-flinn** [comment]
@alistair23 Sorry for the delay on getting back to this PR 😞 . I've checked your branch and see that you were able to get the `Linux Build` job running correctly. I can sign off on this as soon as the conflicts are resolved in the `package.json` file. Thanks!

**Review by joseph-flinn — APPROVED** [review]

**Comment by joseph-flinn** [comment]
@alistair23 Thank you for contribution!

**Comment by joseph-flinn** [comment]
After merging this in and testing the resulting build artifacts, we have found that we cannot build Linux ARM packages with the provided GitHub Action runners as they do not natively support ARM runners. Beekeeper Studio has shown that electron cannot cross-compile electron from x86/amd64 to arm64. We've unfortunately had to revert the changes until we can find time to add a self-host ARM runner.

**Pull request merged**
