### PR TITLE
Desktop fit & finish

### PR DESCRIPTION
**Pull request by Hinton**
Various improvements to improve the fit & finish of the desktop application.

* Add context menu to menu bar icon (mac)
* Add new option "Always show in Dock" (mac)
* Start minimized to menu bar (mac)
* Start on login Windows/Mac/Linux

https://app.asana.com/0/1195018406457675/1198936531478093

Related PR: https://github.com/bitwarden/jslib/pull/212

### CODE REVIEW

**Comment by Hinton** [comment]
Unfortunately I haven't been able to get minimize to tray to restore properly on linux. But the other options should be available.

**Comment by johnhamelink** [comment]
@Hinton RE minimize to tray on Linux: sorry if this is obvious, but did you see this commit? https://github.com/silverscat-3/desktop/commit/cd408308d072eef9967dce46a23f2378531d1a37

**Comment by Hinton** [comment]
@johnhamelink Unfortunately that will only showing the checkbox in settings. The behavior will still be buggy and won't work properly on linux.

**Review by cscharf — APPROVED** [review]
@Hinton , just need to merge master back in and resolve conflicts before this can be merged.

**Review by cscharf — APPROVED** [review]

**Pull request merged**
