### PR TITLE
Distribute mac arm release

### PR DESCRIPTION
**Pull request by nitrocode**
Original PR https://github.com/bitwarden/desktop/pull/793 and ticket https://github.com/bitwarden/desktop/issues/792

In the original PR, I added `--universal` to `pack:mac:mas` and `pack:mac:masdev` and added target `pack:mac:arm64` but I forgot to publish these binaries.

After looking at the windows arm pr https://github.com/bitwarden/desktop/pull/667, it looks like updating the `release.yml` and maybe the `build.yml` github actions ?

Would appreciate help on this if time permits.

cc: @Hinton @cscharf

### CODE REVIEW

**Review by Hinton — COMMENTED** [review]
I suspect we would like to add the arm build to `build.yml` as well (for master branch).

**Comment by joseph-flinn** [comment]
Yes, we would want to add the arm build to the `build.yml` for both the `master` and `rc` branches (`if: github.ref != 'refs/heads/master' || github.ref == 'refs/heads/rc'`) as well as an asset upload in both the `build.yml` and `release.yml` workflows. I would just follow the upload patterns in the respective workflows.

**Comment by dia3olik** [comment]
This will be a godsend since Intel binaries under Rosetta 2 are currently eating ram A LOT...

**Comment by lbibass** [comment]
> I've managed to run Bitwarden as arm64 build locally and based on light testing, there's no apparent breakage on my M1 MBP.
> 
> Here's how I do it:
> set `npm_config_arch` and `npm_config_target_arch` to `arm64` (I'm not sure if cross compilation is possible).
> build.
> 
> The resulting build is arm64 only unfortunately, I tried setting it to universal but CMIIW electron hasn't supported that yet.

I have been unable to get it to compile on my M1 due to some dependencies missing, mainly LZMA-native. I can't compile it any further. 

```npm ERR! Failed to execute '/opt/homebrew/Cellar/node/16.4.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node --module_name=lzma_native --module_path=/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@16.4.0 | darwin | arm64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node" (not found)
npm ERR! node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@16.4.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz

**Comment by AnggaSP** [comment]
> > I've managed to run Bitwarden as arm64 build locally and based on light testing, there's no apparent breakage on my M1 MBP.
> > Here's how I do it:
> > set `npm_config_arch` and `npm_config_target_arch` to `arm64` (I'm not sure if cross compilation is possible).
> > build.
> > The resulting build is arm64 only unfortunately, I tried setting it to universal but CMIIW electron hasn't supported that yet.
> 
> I have been unable to get it to compile on my M1 due to some dependencies missing, mainly LZMA-native. I can't compile it any further.
> 
> ```
> npm ERR! node-pre-gyp info it worked if it ends with ok
> npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
> npm ERR! node-pre-gyp info using node@16.4.0 | darwin | arm64
> npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
> npm ERR! node-pre-gyp info check checked for "/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node" (not found)
> npm ERR! node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> npm ERR! node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> npm ERR! node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> npm ERR! node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@16.4.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
> npm ERR! node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> ```

You may want to try building everything from source

`npm_config_build_from_source`

**Comment by lbibass** [comment]
> > > I've managed to run Bitwarden as arm64 build locally and based on light testing, there's no apparent breakage on my M1 MBP.
> > > Here's how I do it:
> > > set `npm_config_arch` and `npm_config_target_arch` to `arm64` (I'm not sure if cross compilation is possible).
> > > build.
> > > The resulting build is arm64 only unfortunately, I tried setting it to universal but CMIIW electron hasn't supported that yet.
> > 
> > 
> > I have been unable to get it to compile on my M1 due to some dependencies missing, mainly LZMA-native. I can't compile it any further.
> > ```
> > npm ERR! node-pre-gyp info it worked if it ends with ok
> > npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
> > npm ERR! node-pre-gyp info using node@16.4.0 | darwin | arm64
> > npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
> > npm ERR! node-pre-gyp info check checked for "/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node" (not found)
> > npm ERR! node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> > npm ERR! node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> > npm ERR! node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> > npm ERR! node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@16.4.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
> > npm ERR! node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-arm64.tar.gz
> > ```
> 
> You may want to try building everything from source
> 
> `npm_config_build_from_source`

It still fails. 

```1834 error make: *** [Release/nothing.a] Error 1
1834 error gyp ERR! build error
1834 error gyp ERR! stack Error: `make` failed with exit code: 2
1834 error gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
1834 error gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
1834 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
1834 error gyp ERR! System Darwin 20.5.0
1834 error gyp ERR! command "/opt/homebrew/Cellar/node/16.4.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node" "--module_name=lzma_native" "--module_path=/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
1834 error gyp ERR! cwd /Users/lbibass/git/desktop/node_modules/lzma-native
1834 error gyp ERR! node -v v16.4.0
1834 error gyp ERR! node-gyp -v v7.1.2
1834 error gyp ERR! not ok
1834 error node-pre-gyp ERR! build error
1834 error node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/16.4.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node --module_name=lzma_native --module_path=/Users/lbibass/git/desktop/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
1834 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/lbibass/git/desktop/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
1834 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
1834 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
1834 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
1834 error node-pre-gyp ERR! System Darwin 20.5.0
1834 error node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/16.4.0/bin/node" "/Users/lbibass/git/desktop/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
1834 error node-pre-gyp ERR! cwd /Users/lbibass/git/desktop/node_modules/lzma-native
1834 error node-pre-gyp ERR! node -v v16.4.0
1834 error node-pre-gyp ERR! node-pre-gyp -v v0.11.0
1834 error node-pre-gyp ERR! not ok
1835 verbose exit 1```

**Comment by Hinton** [comment]
@lbibass Try compiling with Node 14. The last error log only provides a stacktrace of node-gyp calling make, there are probably more detailed errors somewhere in the build logs which should help you trace down the root cause.

**Comment by lbibass** [comment]
> @lbibass Try compiling with Node 14. The last error log only provides a stacktrace of node-gyp calling make, there are probably more detailed errors somewhere in the build logs which should help you trace down the root cause.

I managed to get it working, but now it fails at notarizing. Any ideas on how to get around that?

**Comment by cscharf** [comment]
> I managed to get it working, but now it fails at notarizing. Any ideas on how to get around that?

It depends what error you're getting, however you likely won't be able to notarize it because your machine identifier and Apple developer profile/certificates are not authorized to do so for our package identifier (which is a good thing 😉 ). Are you getting a technical error or authorization error? You could also locally modify the build action to exclude notarization. You can also use the `masdev` build which I don't believe uses notarization.

**Comment by lbibass** [comment]
> > I managed to get it working, but now it fails at notarizing. Any ideas on how to get around that?
> 
> It depends what error you're getting, however you likely won't be able to notarize it because your machine identifier and Apple developer profile/certificates are not authorized to do so for our package identifier (which is a good thing 😉 ). Are you getting a technical error or authorization error? You could also locally modify the build action to exclude notarization. You can also use the `masdev` build which I don't believe uses notarization.

I've now done the masdev build, but now I get this error when trying to open the built app. 

image

**Comment by fdelucchijr** [comment]
> > > I managed to get it working, but now it fails at notarizing. Any ideas on how to get around that?
> 
> > 
> 
> > It depends what error you're getting, however you likely won't be able to notarize it because your machine identifier and Apple developer profile/certificates are not authorized to do so for our package identifier (which is a good thing 😉 ). Are you getting a technical error or authorization error? You could also locally modify the build action to exclude notarization. You can also use the `masdev` build which I don't believe uses notarization.
> 
> 
> 
> I've now done the masdev build, but now I get this error when trying to open the built app. 
> 
> 
> 
> image
> 
> 

And if you use an `chmod 777 Bitwarden.app` 🤔

**Comment by Hinton** [comment]
To sign and run `masdev` you'll need a provisioning profile valid for your device se https://www.electron.build/code-signing#how-to-export-certificate-on-macos.

The easiest way to just run it with `npm run electron`. If you need a distributed version the `dmg` I seem to remember the dmg version being the eaiest to run (once allowed by GateKeeper). The code signing can be disabled by following the steps at https://www.electron.build/code-signing#how-to-disable-code-signing-during-the-build-process-on-macos

**Comment by AnggaSP** [comment]
Any update from the team on this PR? Anything blocking from preventing this to be work on?

**Comment by lbibass** [comment]
> Any update from the team on this PR? Anything blocking from preventing this to be work on?

The app store already has a Universal Binary

**Comment by Hinton** [comment]
Hi @nitrocode,

Since 1.30 we now publish a universal dmg build on GH and our website. I believe this solves the original issue raised in this PR, and I'll therefore close this.

Thanks for the contribution, and apologies that it took a while for us to address this.

**Pull request closed without merging**
