### PR TITLE
Feature request/prototype: Hot-key window to get and save passwords in any situation

### PR DESCRIPTION
**Pull request by samdesota**
I switched from dashlane to bitwarden today because your open source tools allowed me to build out a feature I've wanted for a long time, a simple hot key window that allows me to add passwords and get passwords in any situation without relying on autocomplete extensions working properly. 

In this PR, by pressing `Ctrl/Cmd + Alt + Space` you get a simple window that allows just that:

Screenshot (7)

I'm happy with this for my personal use, but wanted to share in case you guys were interested in the idea for master, perhaps with a couple more features like enabling/disabling and customization of the shortcut.

### CODE REVIEW

**Comment by kspearrin** [comment]
Thanks for the PR. I am a little confused on the purpose of the new window. Couldn't you just open the regular application window with a hotkey and do the same?

**Comment by mrapogee** [comment]
Yes, but there's a couple of disadvantages:

1. The window isn't right by your cursor
2. If you're in a full screen app or a different desktop, for example, you would be forced to switch desktops on macOs, then re-find your position.
3. Less focused UI for the task, so more information distracting from just grabbing the password

Because the goal of a hot-key window is to optimize for the process of getting the password quickly and it's relatively easy to throw up a window that's focused for the task it makes sense for the workflow. Again, maybe I'm a little bit of a unique bird on this sort of feature, but it's similar to something like the hot-key window with iTerm2, a window that will just overlay wherever you happen to be.

**Comment by Kovah** [comment]
I just wanted to add a similar feature request. I know this from 1Password where you have "1Password Mini", which displays a UI reduced to the minimum that opens on your current desktop after pressing a keyboard shortcut. It will vanish once you selected to open and fill a certain website or you copied credentials.
This is more convenient than switching to the main application or move your mouse to the small icon of the browser extension.
Would highly anticipate getting this merged. 😍

**Comment by mrapogee** [comment]
As a couple more people have chimed in, would be happy to put in a little more effort on this PR to make it reasonable for master with any suggestions from someone more familiar with the code base. 

This is 1passwords implementation: https://support.1password.com/1password-mini-mac/, thanks @Kovah 

Let me know if this is something you're interested in developing out, I think it's good differentiator for power users, something bitwarden probably has more of then the average password manager.

**Comment by Rughalt** [comment]
+1 from me.

It would be also great if on macOS, clicking tray icon - which is somewhat redundant on this system - would bring the small window to top near the icon (as an option). My muscle memory hurts a little because it does not work like that 😉

**Comment by schellenberg** [comment]
+1

**Comment by lukescammell** [comment]
>     2. If you're in a full screen app or a different desktop, for example, you would be forced to switch desktops on macOS, then re-find your position.

This would be a major improvement to fullscreen activities on macOS.

**Comment by djsmentya** [comment]
That is the major feature that I'm looking for. Want to move from 1Password to BitWarden))

**Comment by JReinhold** [comment]
Coming from 1Password, this is definitely the feature I miss the most, it increases the productivity a lot.

**Comment by creshal** [comment]
+1 from me, it's the only missing feature that keeps me from migrating our whole org (30+ users) over to Bitwarden.

What needs to be done still to make it ready for merging? Other than fixing the CI checks?

**Comment by shawnz** [comment]
This is excellent, please add this! I agree with the other posters that this is in fact much more convenient than just opening the main application window by hotkey.

**Comment by eliykat** [comment]
Hi @samdesota, I'm currently reviewing community PRs. If you're still interested in having this one merged, please sign the Contributor License Agreement ([info here](https://github.com/bitwarden/desktop/pull/231#issuecomment-596086640), and reply here to let me know you've done it. (Please @ me to make sure I see it.) I'll then schedule it for further review by our Product & Engineering team.

If I don't hear from you in the next couple of weeks, I'll close this PR. However, this is just housekeeping, I can reopen it if required.

**Pull request closed without merging**
