### PR TITLE
Hide email address in Sends

### PR DESCRIPTION
**Pull request by eliykat**
Desktop implementation of https://github.com/bitwarden/server/pull/1234.

### CODE REVIEW

**Review by cscharf — COMMENTED** [review]
Looks good, does this need latest jslib merged as well?

**Comment by eliykat** [comment]
Yes, all angular clients depend on the jslib changes, so this can wait until then.

**Comment by eliykat** [comment]
Note: the build here is broken by @MGibson1's unrelated changes to jslib here: https://github.com/bitwarden/jslib/commit/cfc76878154c5b292b729e2909bec1848f5cc23c.

**Review by addisonbeck — APPROVED** [review]
I went ahead and fixed that build error. Feel free to dump the commit if you want it fixed separately, @eliykat, but it's just a service DI change so the insignificant invasiveness is probably worth having a functioning build.

**Comment by eliykat** [comment]
Thanks @addisonbeck, I just wasn't sure whether to fix it here or let Matt fix it in a separate PR. Appreciate the help.

**Pull request merged**
